-- ETAPA 01 DO PROJETO: CRIAÇÃO DE BANCO DE DADOS, TABELAS E DEFINIÇÃO DO RELACIONAMENTO
CREATE DATABASE escola

USE escola

CREATE TABLE Turma(
Id INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
Nome VARCHAR(20) NOT NULL,
Ativo BIT
);

CREATE TABLE Aluno(
Id INT IDENTITY (1,1) PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
DataNascimento DATE NOT NULL,
Sexo CHAR NOT NULL,
TotalFaltas INT,
Id_Turma INT FOREIGN KEY REFERENCES Turma(Id)
);